# Generated by Django 4.2.6 on 2024-07-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='link_to_media',
            field=models.URLField(blank=True, verbose_name='ссылка на СМИ'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='photo_album_url',
            field=models.URLField(blank=True, verbose_name='ссылка на фото-альбом'),
        ),
    ]
