# Generated by Django 4.2.6 on 2024-07-21 12:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('achievement', '0007_achievementorder_delete_mainachievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievementorder',
            name='achievement',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='achievement.achievement', verbose_name='достижение'),
        ),
        migrations.AlterField(
            model_name='achievementorder',
            name='order',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='порядок'),
        ),
    ]
