# Generated by Django 4.2.6 on 2024-08-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hardathon', '0002_alter_hardathon_documents_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardathon',
            name='main_organizer_word',
            field=models.TextField(verbose_name='слово главного организатора'),
        ),
    ]
